### ISSUE TITLE
handle `MySQL server has gone away` as user error

### ISSUE THREAD

**Issue by kacurez** [keboola/db-writer-mysql#10]
imho najcastejsie je to sposobene pretazenim mysql servru datami/query a to by sa potom malo poladit na strane klienta(zmensenim dat, zmensenim casoveho okna inkrementu..)

**Comment by ErikZigo** [comment]
Mam na to dalsi ticket. Driv se to mozna i jako user error logovalo?

**Comment by MiroCillik** [comment]
To by malo byt vyriesene tymto https://github.com/keboola/db-writer-mysql/commit/8bbf369b68a67adc7fa6ec1bc01d512386000b95.

Vsetky \PDOException sa konvertuju na UserException:
https://github.com/keboola/db-writer-common/blob/master/src/Application.php#L86
