### ISSUE TITLE
provide valuable logs

### ISSUE THREAD

**Issue by kacurez** [keboola/db-writer-mysql#9]
zalogovat len jednu hlasku na konci jobu je dost malo, na debug chyby to nestaci. Ak chcem zistit ktora tabulka robi problemy napr tu:
![image](https://user-images.githubusercontent.com/1412120/40165395-22f2782c-59bc-11e8-90e2-5a93665ec417.png)
Tak z toho logu nic nevycitam a musim to pustat tabulku po tabulke co pri 10-15 tabulkach zaberie cas, navyse ta chyba naznacuje ze sa na server vobec nepripojil.

**Comment by Halama** [comment]
máš stack trace v PT ne?

**Comment by Halama** [comment]
není tam takže to je chyba v handlování chyb

**Comment by Halama** [comment]
zřejmě to spadlo sem https://github.com/keboola/db-writer-mysql/blob/2a096f028769bacc59e7abb069efec68ebe234d6/run.php#L51

**Comment by Halama** [comment]
^ takže fixnout tohle primárně

**Comment by kacurez** [comment]
Ja by som pridal logovanie zaciatku a konca zapisu tabulky do db, niec ako

```
start writing table xyz
finished writing table xyz
```

potom by v tomto pripade bolo zrejme ktora tabulka robi problem, v internal error vidim len `MySQL server has gone away [] []` ale nie id tabulky pri ktorej to spadlo.

**Comment by Halama** [comment]
jo jak píšu tak to logování internal erroru je špatně to základní problém.

**Comment by Halama** [comment]
Jinak at to za běhu klidně loguje start a konec...

**Comment by Halama** [comment]
je to přesně to samé co tady https://github.com/keboola/php-component/issues/29 bohužel většina ex i db writerů to má špatně a jsou nedebugovatelný

**Comment by kacurez** [comment]
jasne treba minimalne vyriesit logovanie tej chyby, no ak by tam bolo aj info a zaciatku a konci zapisu tak by to imho klient vydebugoval sam bez ticketu na zd

**Comment by MiroCillik** [comment]
Fixed in https://github.com/keboola/db-writer-mysql/commit/8bbf369b68a67adc7fa6ec1bc01d512386000b95
